### PR TITLE
Add <Modal /> component (with stories) and move sign in to a modal.

### PR DESCRIPTION
**Pull request by ghost**
Did this so that the /auth/signin path can be retired, it may be very confusing to the end-user to have two paths (auth and account) that are, to them, just for account entry and information.

Aside from that, I think it fits better considering the architecture, since everything relies on a higher level component that gets refreshed anyway, and it gets rid of some router pushes.

### CODE REVIEW

**Comment by kearfy** [comment]
That's nice! I would still like a direct path for a signin page (for SEO) but we can just pop up the modal at that point or render the modal content on that page

**Comment by ghost** [comment]
Don't have my Cloudflare login at the moment, will have to run through those errors later.

**Comment by kearfy** [comment]
Interesting how the linting action did not catch this, will look into that.

```
12:15:49.153 | ./components/Icon/IconBase.tsx:26:68
-- | --
12:15:49.153 | Type error: Element implicitly has an 'any' type because expression of type 'ColorType' can't be used to index type '{ Tint: string; Light: string; LightTintLight: string; LightTintLightHover: string; LightTintDark: string; LightTintDarkHover: string; Dark: string; DarkTintLight: string; DarkTintLightHover: string; ... 4 more ...; Green: string; }'.
12:15:49.154 | Property 'Transparent' does not exist on type '{ Tint: string; Light: string; LightTintLight: string; LightTintLightHover: string; LightTintDark: string; LightTintDarkHover: string; Dark: string; DarkTintLight: string; DarkTintLightHover: string; ... 4 more ...; Green: string; }'.
12:15:49.154 |  
12:15:49.154 | 24 \|             <style type="text/css">
12:15:49.154 | 25 \|                 {color
12:15:49.154 | > 26 \|                     ? `.svg-${icon}-styles * { ${styles} stroke: ${Color[color]}; fill: ${Color[color]}; color: ${Color[color]}; }`
12:15:49.154 | \|                                                                    ^
12:15:49.154 | 27 \|                     : `
12:15:49.154 | 28 \|           .svg-${icon}-styles * { ${styles} stroke: ${Color.Light}; fill: ${Color.Light}; color: ${Color.Light}; }
12:15:49.155 | 29 \|         @media (prefers-color-scheme: dark) {
```

**Comment by kearfy** [comment]
^^ Maybe we have to extend the action with a `tsc --pretty`, then the typescript compiler also goes over it

**Comment by ghost** [comment]
Alrighty, seems to be fixed!

**Comment by kearfy** [comment]
@Leafeling I pushed a few style & logical changes, are they okay with you?

**Comment by ghost** [comment]
I made a little edit so that these kinds of timings can be edited from one place for the whole module.

**Comment by ghost** [comment]
Now that that's done, this is all good to be merged by me. Looking forward to it! :)

**Review by kearfy — APPROVED** [review]
Looks good, nice addition!

**Pull request merged**
